src/Entity/Vlasnik.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Vlasnik
 *
 * @ORM\Table(name="vlasnik")
 * @ORM\Entity
 */
class Vlasnik
{
    /**
     * @var int
     *
     * @ORM\Column(name="Vlasnik_ID", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $vlasnikId;

    /**
     * @var string|null
     *
     * @ORM\Column(name="Naziv_vlasnika", type="string", length=50, nullable=true, options={"default"="NULL"})
     */
    private $nazivVlasnika;

    /**
     * @var string|null
     *
     * @ORM\Column(name="Kontakt_broj", type="string", length=50, nullable=true, options={"default"="NULL"})
     */
    private $kontaktBroj;

    /**
     * @var string|null
     *
     * @ORM\Column(name="Elektronska_posta", type="string", length=50, nullable=true, options={"default"="NULL"})
     */
    private $elektronskaPosta;

    public function getVlasnikId(): ?int
    {
        return $this->vlasnikId;
    }

    public function getNazivVlasnika(): ?string
    {
        return $this->nazivVlasnika;
    }

    public function setNazivVlasnika(?string $nazivVlasnika): self
    {
        $this->nazivVlasnika = $nazivVlasnika;

        return $this;
    }

    public function getKontaktBroj(): ?string
    {
        return $this->kontaktBroj;
    }

    public function setKontaktBroj(?string $kontaktBroj): self
    {
        $this->kontaktBroj = $kontaktBroj;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->elektronskaPosta;
    }

    public function setEmail(?string $elektronskaPosta): self
    {
        $this->elektronskaPosta = $elektronskaPosta;

        return $this;
    }


}

templates/default/_flash_messages.html.twig
{% if app.request.hasPreviousSession %}
    <div class="messages">
        {% for type, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-dismissible alert-{{ type }} fade in" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}

templates/default/_form.html.twig
{{ form_start(form, {attr: attr|default({})}) }}
    {{ form_widget(form) }}

<div class="section">
    <button type="submit" class="{{ button_css|default("btn btn-primary") }}">
        <i class="fa fa-save" aria-hidden="true"></i> {{ 'potvrdi' }}
    </button>

    <a href="{{ path('app_index') }}" class="btn btn-primary btn-info">
        <i class="fa fa-eye" aria-hidden="true"></i> {{ 'pocetna' }}
    </a>
</div>

{{ form_end(form) }}

templates/default/appIndex.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'app_index' %}

{% block main %}
    <div class="page-header">
        <div class="alert alert-primary" role="alert">
            <h3>{{ 'Welcome! ' }}<b>{{ user.email }}</b></h3>
        </div>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
        <table class="table table-striped table-dark">
            <thead>
            <tr>
                <th scope="col">Entiteti</th>
                <th scope="col">Dodaj novi element</th>
                <th scope="col">Prikazi vrijednosti</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-map-marker"></i>Lokacija</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('lokacija_nova') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('lokacija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-user"></i>Vlasnik</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('vlasnik_novi') }}">
                        <i class="fa fa-list-ul" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('vlasnik_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-list-alt"></i>Softver</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('software_novi') }}">
                        <i class="fa fa-list" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('software_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-hdd"></i>Hardver</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('hardware_novi') }}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('hardware_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-tasks"></i>Kategorija</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('kategorija_nova') }}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('kategorija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-home"></i>Ustanova</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('ustanova_nova') }}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('ustanova_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-tent"></i>Organizacija</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('ustanova_nova') }}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('organizacija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-question-sign"></i>Namjena</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('namjena_nova') }}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('namjena_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-info-sign"></i>Specijalizacija</th>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('specijalizacija_nova') }}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'Dodaj' }}
                    </a></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('specijalizacija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-flash"></i>Hardver-Softver</th>
                <td></td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('hw_sw_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-wrench"></i>Lokacija-Specijalizacija</th>
                <td>
                   </td>
                <td><a class="btn btn-primary btn-sm" href="{{ path('lok_spec_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            </tbody>
        </table>
    {% endif %}
    <br>

    {% if not is_granted('ROLE_ADMIN') %}
        <table class="table table-striped table-dark">
            <thead>
            <tr>
                <th scope="col">Entiteti</th>
                <th scope="col">Prikazi vrijednosti</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-map-marker"></i>Lokacija</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('lokacija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-user"></i>Vlasnik</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('vlasnik_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-list-alt"></i>Softver</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('software_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-hdd"></i>Hardver</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('hardware_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-tasks"></i>Kategorija</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('kategorija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-home"></i>Ustanova</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('ustanova_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-tent"></i>Organizacija</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('organizacija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-question-sign"></i>Namjena</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('namjena_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-info-sign"></i>Specijalizacija</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('specijalizacija_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-flash"></i>Hardver-Softver</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('hw_sw_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            <tr>
                <th scope="row"><i class="glyphicon glyphicon-wrench"></i>Lokacija-Specijalizacija</th>
                <td><a class="btn btn-primary btn-sm" href="{{ path('lok_spec_index') }}">
                        <i class="fa fa-edit" aria-hidden="true"></i> {{ 'Prikazi' }}
                    </a></td>
            </tr>
            </tbody>
        </table>
    {% endif %}
    <br>
{% endblock %}

{% block sidebar %}
    {{ parent() }}
    <div class="alert alert-info" role="alert">
        <h7>Pretraži hardware i software na lokaciji</h7>
    </div>
    <form method="post">
        <div class="input-group mb-3">
            {{ form_start(form) }}
            {{ form_row(form.brojUcionice) }}
            <button type="submit" class="btn btn-sm btn-primary">
                <i class="fa fa-arrow-alt-circle-right" aria-hidden="true"></i> {{ "Run query" }}
            </button>
            {{ form_end(form) }}
        </div>
    </form>

{% endblock %}

templates/default/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="page-header">
        <h1><b>{{ 'Dobrodosli!' }}</b></h1>
    </div>
        <div class="alert alert-light" role="alert">
            <div class="section">
                <i>Ovo je web aplikacija koja omogućava pregled opreme odsjeka za stručne studije.<br>
                        To uključuje pregled hardverske i softverske opreme. Opremu je moguće pretraživati prema
                        različitim
                        kriterijima.<br>
                        U slučaju da se prijavite kao admin, moguće je dodavati nove te izmjenjivati ili brisati već
                        postojeće podatke.</i>
            </div>
        </div>

    <div class="container">
        <div class="col-sm-6">
            <div class="jumbotron">
                <p>Novi korisnik? <b>Registrirajte se!</b></p>
                <a href="{{ path('app_register') }}" class="btn btn-lg btn-primary">
                    <i class="fa fa-user-plus" aria-hidden="true"></i> {{ 'register' }}
                </a>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="jumbotron">
                <br>
                <p>Postojeci korisnik? <b>Prijavite se!</b></p>
                <a href="{{ path('app_login') }}" class="btn btn-lg btn-primary">
                    <i class="fa fa-check-square-o" aria-hidden="true"></i> {{ 'login' }}
                </a>
            </div>
        </div>
    </div>
{% endblock %}